# Root-level test scripts in this repository are executable diagnostics,
# not pytest-style test modules. Ignore them during pytest collection.
collect_ignore = [
    "test_absentee_courses.py",
    "test_absentee_fix.py",
    "test_absentee_workflow.py",
    "test_api_courses.py",
    "test_app_startup.py",
    "test_attendance_generation.py",
    "test_bucket_clear.py",
    "test_bucket_deletion.py",
    "test_comprehensive.py",
    "test_consolidated_format.py",
    "test_course_filtering.py",
    "test_generate_absentee_html.py",
    "test_download_debug.py",
    "test_optimizations.py",
    "test_pdf_generation.py",
    "test_performance_optimizations.py",
    "test_preview.py",
    "test_preview_approved.py",
    "test_semester_display.py",
    "test_supabase_users.py",
    "test_ui_improvements.py",
]
